Added logger
hunte-r/php-cource-plesk pull request #11
Opened 2022-02-03 06:53 UTC by hunte-r

2022-02-16 12:34 UTC, ova777 requested changes
1. Есть немного замечаний по логгеру, но вообще всё сделано правильно.
2. Нужно добавить .gitignore, и прописать туда папку /vendor, и желательно .phpunit.result.cache. Суть в том, что бы любой мог склонироваться, сделать composer install, composer test, и при этом не было файлов, которые git предлагает закоммитить.

2022-02-16 12:34 UTC, ova777 commented on src/Logger/AbstractLogger.php
> +    abstract public function log(string $msg): void;
Этот метод может быть protected, т.к. снаружи им никто не пользуется, только "наследники" этого класса, и к тому же если бы он использовался извне - его нужно было бы описать в интерфейсе.

2022-02-16 12:34 UTC, ova777 commented on src/Logger/FakeLogger.php
> +    public function err (string $msg): void
В этом классе не обязательно реализовывать методы err, warn, info, достаточно того, что есть пустой метод log, и в итоге эти методы будут вызывать пустой log, и ничего логгироваться и так не будет.

2022-02-16 12:34 UTC, ova777 commented on src/Logger/LoggerFactory.php
> +    public static function getInstance(array $config = null)
Здесь не плохо бы указать return type, он тут будет `self`

2022-02-17 03:47 UTC, hunte-r commented on src/Logger/AbstractLogger.php
> +    public function info (string $msg): void
Исправил везде.

2022-02-17 03:52 UTC, hunte-r commented on src/Logger/AbstractLogger.php
> +    abstract public function log(string $msg): void;
Поправил.

2022-02-17 03:53 UTC, hunte-r commented on src/Logger/FakeLogger.php
> +    public function err (string $msg): void
Спасибо, поправил.

2022-02-17 03:54 UTC, hunte-r commented on src/Logger/LoggerFactory.php
> +    public static function getInstance(array $config = null)
Поправил.

2022-02-17 04:02 UTC, hunte-r commented on src/Logger/LoggerFactory.php
> +    private static $instance;
Поправил. Про знак вопроса перед типом посмотрел, записал. Спасибо.

2022-02-17 04:38 UTC, ova777 requested changes
Всего одно замечание, поправь, и будет совсем всё ок!

2022-02-17 04:38 UTC, ova777 commented on src/Logger/AbstractLogger.php
> +    abstract protected function log(string $msg): void;
Здесь ты сделал метод protected, а в наследниках он остался public

2022-02-17 05:58 UTC, hunte-r commented on src/Logger/AbstractLogger.php
> +    abstract protected function log(string $msg): void;
Исправил.

2022-02-17 06:21 UTC, ova777 requested changes
Теперь всё ок, но я решил все же прогнать код линтером (жаль что ты его не подключил), и нашлось еще несколько замечаний (ну это уже что бы совсем всё хорошо было):
- Task1::binarySum - не указан модификатор доступа (public)
- Task8.php, строка 37 - не хватает пробела после запятой
- Названия методов должны быть с маленькой буквы (Task4Test::AddDigitsProvider, Task7Test::IsHappyWrongSymbolsProvider)
- Task7Test::testIsHappyOdd, строка 69 - строка не должна быть длинне 120 символов, поэтому лучше разбить на несколько строк:
```
self::assertEquals(
  '[ERR] Exception: Input value must contain even number of digits',
  $actualExceptionMessage
);
```

2022-02-17 07:55 UTC, ova777 approved these changes

2022-02-17 07:56 UTC, merged